title: Pengyu Xu (徐鹏宇)
position: Ph.D. Student in Computer Science
affiliation: Beijing Jiaotong University.<br>No.3 Shangyuancun, Haidian District, Beijing, China
email: pengyuxu@bjtu.edu.cn
email_link: mailto:pengyuxu@bjtu.edu.cn
github_link: https://github.com/stxupengyu
google_scholar: https://scholar.google.com.hk/citations?user=W2RlvvAAAAAJ&hl=zh-CN
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: A second-year PhD candidate at Beijing Jiaotong University (BJTU)
remote_theme: yaoyao-liu/strata-academic
